import { createApp } from "./app.js";
import { seedAdmin } from "./auth.js";
import { config } from "./config.js";
import { createTranscriptClassifier } from "./classifier.js";
import { logger } from "./logger.js";
import { CallOrchestrator } from "./orchestrator.js";
import { initializeStore } from "./runtime-store.js";
import { createTelephonyAdapter } from "./telephony.js";
import { installShutdown } from "./shutdown.js";
import { CampaignDialer } from "./campaigns.js";

const { store, authStore } = await initializeStore();
await seedAdmin(authStore);
const adapter = createTelephonyAdapter();
const classifier = createTranscriptClassifier();
const calls = new CallOrchestrator(store, adapter, classifier);
await calls.initialize();
const campaignDialer = new CampaignDialer(store, calls);
const { app, closeSseStreams } = createApp({ store, adapter, classifier, calls, authStore, campaignDialer });
campaignDialer.start();
const server = app.listen(config.port, () => logger.info({ port: config.port, mode: adapter.mode }, "MKTR Voice API listening"));
installShutdown({ server, calls, closeSseStreams, beforeDrain: () => campaignDialer.close(), closeStore: () => store.close(), logger });
