applications/mod_commands
applications/mod_dptools
applications/mod_avmd
dialplans/mod_dialplan_xml
endpoints/mod_sofia
endpoints/mod_loopback
event_handlers/mod_event_socket
formats/mod_sndfile
formats/mod_tone_stream
loggers/mod_console
loggers/mod_logfile
